name: Draw keymap
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/glove80.keymap'
      - 'config/*.dtsi'
      - 'graphic/config.yaml'
      - '.github/workflows/draw-keymap.yml'

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: 'config/*.keymap'
      config_path: graphic/config.yaml
      output_folder: graphic
      commit_message: 'Draw keymap'
      install_branch: main